### ISSUE TITLE
Wired devices (switches/USG) show up as locations

### ISSUE THREAD

**Issue by bc2297** [DouweM/homebridge-unifi-occupancy#19]
Mentioned in #17 

**Describe The Bug:**
Sensors are being created for disabled APs, and also for wired devices

**Expected behavior:**
Would expect devices to not be created

**Logs:**
[unifi.txt](https://github.com/DouweM/homebridge-unifi-occupancy/files/11023631/unifi.txt)

from v2/api/site/default/device, too big to post directly

**Plugin Config:**

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by DouweM** [comment]
@bc2297 Disabled devices are now excluded in v1.2.6, but we have to include switches as you have the option of enabling accessories for wired clients in settings. I recommend mapping the switches to a room that also has an access point so that they don't show up by themselves. Is that an option?

**Comment by bc2297** [comment]
yep this works for me
