### ISSUE TITLE
My Unifi AP's aren't being detected

### ISSUE THREAD

**Issue by mbhforum** [DouweM/homebridge-unifi-occupancy#20]
**Describe Your Problem:**

My AP's aren't being detected by this plug-in.  I tried using friendly name and MAC address and neither are working.  I am including debug log and config.json for one of my AP's below. 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.

[4/3/2023, 12:41:31 PM] [UnifiOccupancy] Found room: Family Room AP (Family Room AP)
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
            "accessPointAliases": [
                {
                    "accessPoint": " Family Room AP",
                    "alias": "Family Room AP (Family Room AP)"
                },
                {
                    "accessPoint": "Family Room AP (Family Room AP)",
                    "alias": "Family Room"
                }

**Screenshots:**

**Environment:**

* **Plugin Version**:  1.2.7
* **Homebridge Version**:   1.6
* **Node.js Version**: .   Not Sure
* **NPM Version**: . Not Sure 
* **Operating System**:  Docker (ouzu)

**Comment by mbhforum** [comment]
I misunderstood how the plug-in worked and now have it working.

**Comment by DouweM** [comment]
@mbhforum Glad to hear it! Anything I can clarify in the README or settings interface?

**Comment by mbhforum** [comment]
> @mbhforum Glad to hear it! Anything I can clarify in the README or settings interface?

I was expecting my AP's to show up as a device in HomeKit, so it cannot hurt to say this is just for virtual assignment of rooms.  Also - is there a way to ignore the switches,UDM pro, etc from showing up in HomeKit?  I tried using the device/host exclusion option but they still show under Default Room.
