### ISSUE TITLE
Unifi Switches, UDM, etc. showing up as Occupancy Sensors

### ISSUE THREAD

**Issue by mbhforum** [DouweM/homebridge-unifi-occupancy#21]
**Describe The Bug:**

I have 3 types of Unifi devices showing up as Occupancy Sensors, even though I have tried using Host Name Exclusions.  Devices are:

UDM-Pro
LTE Professional
POE Switches

**To Reproduce:**

As an example, Add /DM/ to Host Name exclusions and restart Homebridge.  Despite this, DM-Pro Marc will show up as an occupancy sensor in my Default Room in Homekit. 

**Expected behavior:**

I expect my firewall, switched and U-LTE-Pro to not show up as occupancy sensors.

**Logs:**

[4/13/2023, 3:38:27 PM] [UnifiOccupancy] Accessory status unchanged: "DM-Pro Marc" inactive

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
                {
                    "label": "DM Pro",
                    "namePatterns": [
                        "/DM/"
                    ],
                    "roomAccessory": false,
                    "homeAccessory": false,
                    "roomCatchallAccessory": false,
                    "homeCatchallAccessory": false,
                    "lazy": false
                }

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.7
* **Homebridge Version**:  1.6
* **Node.js Version**: v18.13.0
* **NPM Version**: 
* **Operating System**:  Docker - Ubuntu Focal Fossa (20.04.5 LTS)
--

**Comment by bc2297** [comment]
I previously brought this up and was given this advice https://github.com/DouweM/homebridge-unifi-occupancy/issues/19#issuecomment-1484147623
